def getBVDColDict():
    '''Map historical columns to wrds columns'''
    column_match = {
        'ï»¿BvD ID number': 'bvdid', 
        'Consolidation code': 'conscode', 
        'Filing type': 'filing_type', 
        'Closing date': 'closdate',
        'Number of months': 'nr_months',
        'Audit status': 'audstatus', 
        'Accounting practice': 'accpractice',
        'Source (for publicly quoted companies)': 'source', 
        'Original units': 'orig_units',
        'Original currency': 'orig_currency', 
        'Exchange rate from original currency': 'exchrate',
        'Fixed assets': 'fias',
        'Intangible fixed assets': 'ifas',
        'Tangible fixed assets': 'tfas',
        'Other fixed assets': 'ofas',
        'Current assets': 'cuas',
        'Stock': 'stok',
        'Debtors': 'debt',
        'Other current assets': 'ocas',
        'Cash & cash equivalent': 'cash',
        'Total assets': 'toas',
        'Shareholders funds': 'shfd',
        'Capital': 'capi',
        'Other shareholders funds': 'osfd',
        'Non-current liabilities': 'ncli',
        'Long term debt': 'ltdb',
        'Other non-current liabilities': 'oncl',
        'Provisions': 'prov',
        'Current liabilities': 'culi',
        'Loans': 'loan',
        'Creditors': 'cred',
        'Other current liabilities': 'ocli',
        'Total shareh. funds & liab.': 'tshf',
        'Working capital': 'wkca', 
        'Net current assets': 'ncas',
        'Enterprise value': 'enva', 
        'Number of employees': 'empl',
        'Operating revenue (Turnover)': 'opre', 
        'Sales': 'turn', 
        'Costs of goods sold': 'cost',
        'Gross profit': 'gros',
        'Other operating expenses': 'oope',
        'Operating P/L [=EBIT]': 'oppl',
        'Financial revenue': 'fire',
        'Financial expenses': 'fiex',
        'Financial P/L': 'fipl',
        'P/L before tax': 'plbt',
        'Taxation': 'taxa',
        'P/L after tax': 'plat',
        'Extr. and other revenue': 'exre',
        'Extr. and other expenses': 'exex',
        'Extr. and other P/L': 'extr',
        'P/L for period [=Net income]': 'pl',
        'Export revenue': 'expt',
        'Material costs': 'mate',
        'Costs of employees': 'staf',
        'Depreciation & Amortization': 'depr',
        'Interest paid': 'inte',
        'Research & Development expenses': 'rd',
        'Cash flow': 'cf',
        'Added value': 'av',
        'EBITDA': 'ebta',
        'ROE using P/L before tax (%)': 'rshf',
        'ROCE using P/L before tax (%)': 'rcem',
        'ROA using P/L before tax (%)': 'rtas',
        'ROE using Net income (%)': 'roe',
        'ROCE using Net income (%)': 'roce',
        'ROA using Net income (%)': 'roa',
        'Profit margin (%)': 'prma',
        'Gross margin (%)': 'grma',
        'EBITDA margin (%)': 'etma',
        'EBIT margin (%)': 'ebma',
        'Cash flow / Operating revenue (%)': 'cfop',
        'Enterprise value / EBITDA (x)': 'evet',
        'Market cap / Cash flow from operations (x)': 'mkcf',
        'Net assets turnover (x)': 'nat',
        'Interest cover (x)': 'ic',
        'Stock turnover (x)': 'stot',
        'Collection period (days)': 'coll',
        'Credit period (days)': 'crpe', 
        'Export revenue / Operating revenue (%)': 'exop',
        'R&D expenses / Operating revenue (%)': 'rdop',
        'Current ratio (x)': 'curr',
        'Liquidity ratio (x)': 'liqr',
        'Shareholders liquidity ratio (x)': 'shlq',
        'Solvency ratio (Asset based) (%)': 'solr',
        'Solvency ratio (Liability based) (%)': 'soll',
        'Gearing (%)': 'gear',
        'Profit per employee (th)': 'ppe',
        'Operating revenue per employee (th)': 'tpe',
        'Costs of employees / Operating revenue (%)': 'sct',
        'Average cost of employee (th)': 'ace',
        'Shareholders funds per employee (th)': 'sfpe',
        'Working capital per employee (th)': 'wcpe',
        'Total assets per employee (th)': 'tape',
        'Estimated operating revenue': 'df_oprev', 
        'Estimated employees': 'df_employees',
        'Operating revenue original range value': 'op_rev_original_range_value',
        'Employees  original range value': 'emp_orig_range_value'
    }    
    return column_match